### ISSUE TITLE
Better error message on invalid JWT

### ISSUE THREAD

**Issue by danielamiao** [momentohq/client-sdk-dotnet#245]
MOMENTO_AUTH_TOKEN is spelled wrong (or is not provided), we could say that explicitly instead of the generic “invalid jwt”. Right now if the token is null we also say "invalid jwt" which isn't very helpful.

```
ENTO_AUTH_TOKEN=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ2aXIiLCJjcCI6ImNvbnRyb2wuY2VsbC1hbHBoYS1kZXYucHJlcHJvZC5hLm1vbWVudG9ocS5jb20iLCJjIjoiY2FjaGUuY2VsbC1hbHBoYS1kZXYucHJlcHJvZC5hLm1vbWVudG9ocS5jb20ifQ.rqm1naR6x956OGmN2_jbWxwdkh_7ErNNBP0SNNTq_dFfON3tD7mxRPx7GJsDwhBa_w3N_bKXr4li5NVugTezxA dotnet run --project MomentoApplication 

Unhandled exception. Momento.Sdk.Exceptions.InvalidArgumentException: invalid jwt passed
   at Momento.Sdk.Internal.JwtUtils.DecodeJwt(String jwt)
   at Momento.Sdk.SimpleCacheClient..ctor(IConfiguration config, String authToken, UInt32 defaultTtlSeconds, ILoggerFactory loggerFactory)
   at MomentoApplication.Program.Main(String[] args) in /Users/ratanasv/workspace/client-sdk-dotnet/examples/MomentoApplication/Program.cs:line 21
   at MomentoApplication.Program.<Main>(String[] args)
```

**Comment by cprice404** [comment]
related: https://github.com/orgs/momentohq/projects/30/views/1
